// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SantiagoConlago_Examen1P.Data;

#nullable disable

namespace SantiagoConlago_Examen1P.Migrations
{
    [DbContext(typeof(SantiagoConlago_Examen1PContext))]
    [Migration("20241028155514_SCtablita3")]
    partial class SCtablita3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SantiagoConlago_Examen1P.Models.SantiagoConlago_model", b =>
                {
                    b.Property<int>("SantiagoConlago_modelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SantiagoConlago_modelId"));

                    b.Property<DateTime>("SCDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SCDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SCGarantia")
                        .HasColumnType("bit");

                    b.Property<decimal?>("SCPrecio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SCVideojuego")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SantiagoConlago_modelId");

                    b.ToTable("SantiagoConlago_model");
                });
#pragma warning restore 612, 618
        }
    }
}
